export default {
  id: "agy",
  alias: "agy",
  display: {
    name: "AGY",
    icon: "smart_toy",
    color: "#8B5CF6",
    textIcon: "AG",
  },
  category: "oauth",
  authType: "oauth",
  hasOAuth: true,
  transport: {
    format: "antigravity",
    executor: "antigravity",
    baseUrls: [
      "https://daily-cloudcode-pa.googleapis.com",
      "https://cloudcode-pa.googleapis.com",
    ],
    urlBuilder: function buildAntigravityUrl(base, model, stream) { const path = stream ? "/v1internal:streamGenerateContent?alt=sse" : "/v1internal:generateContent"; return `${base}${path}`; },
    headers: {
      "Content-Type": "application/json",
      "User-Agent": "antigravity/cli/1.1.5 (aidev_client; os_type=darwin; arch=arm64; auth_method=consumer)",
    },
    auth: {
      combined: true,
      header: "Authorization",
      scheme: "bearer",
    },
  },
  oauth: {
    clientIdEnv: "ANTIGRAVITY_OAUTH_CLIENT_ID",
    clientSecretEnv: "ANTIGRAVITY_OAUTH_CLIENT_SECRET",
    clientIdDefault: process.env.ANTIGRAVITY_OAUTH_CLIENT_ID || "",
    clientSecretDefault: process.env.ANTIGRAVITY_OAUTH_CLIENT_SECRET || "",
  },
  models: [
    {
      id: "gemini-3.7-flash-high",
      name: "Gemini 3.7 Flash (High)",
      contextLength: 1048576,
      maxOutputTokens: 65536,
      supportsReasoning: true,
      supportsVision: true,
      toolCalling: true,
    },
    {
      id: "gemini-3.7-flash-medium",
      name: "Gemini 3.7 Flash (Medium)",
      contextLength: 1048576,
      maxOutputTokens: 65536,
      supportsReasoning: true,
      supportsVision: true,
      toolCalling: true,
    },
    {
      id: "gemini-3.7-flash-low",
      name: "Gemini 3.7 Flash (Low)",
      contextLength: 1048576,
      maxOutputTokens: 65536,
      supportsReasoning: true,
      supportsVision: true,
      toolCalling: true,
    },
    {
      id: "gemini-3.7-flash-tiered",
      name: "Gemini 3.7 Flash (Tiered)",
      contextLength: 1048576,
      maxOutputTokens: 65536,
      supportsReasoning: true,
      supportsVision: true,
      toolCalling: true,
    },
    {
      id: "gemini-pro-agent",
      name: "Gemini 3.1 Pro (High)",
      contextLength: 1048576,
      maxOutputTokens: 65535,
      supportsReasoning: true,
      supportsVision: true,
      toolCalling: true,
    },
    {
      id: "gemini-3.1-pro-low",
      name: "Gemini 3.1 Pro (Low)",
      contextLength: 1048576,
      maxOutputTokens: 65535,
      supportsReasoning: true,
      supportsVision: true,
      toolCalling: true,
    },
    {
      id: "gemini-3.1-flash-lite",
      name: "Gemini 3.1 Flash Lite",
      contextLength: 1048576,
      maxOutputTokens: 65535,
      toolCalling: true,
    },
    {
      id: "claude-opus-4-6-thinking",
      name: "Claude Opus 4.6 (Thinking)",
      contextLength: 1048576,
      maxOutputTokens: 65536,
      supportsReasoning: true,
      supportsVision: true,
      toolCalling: true,
    },
    {
      id: "claude-sonnet-4-6",
      name: "Claude Sonnet 4.6 (Thinking)",
      contextLength: 1048576,
      maxOutputTokens: 65536,
      supportsReasoning: true,
      supportsVision: true,
      toolCalling: true,
    },
    {
      id: "gpt-oss-120b-medium",
      name: "GPT-OSS 120B (Medium)",
      contextLength: 131072,
      maxOutputTokens: 32768,
      supportsReasoning: true,
      toolCalling: true,
    },
  ],
  passthroughModels: true,
};
