export default {
  id: "cheaperinference",
  alias: "cinf",
  display: {
    name: "CheaperInference",
    icon: "savings",
    color: "#16A34A",
    textIcon: "CI",
    website: "https://cheaperinference.com",
  },
  category: "apikey",
  authType: "apikey",
  transport: {
    format: "openai",
    executor: "cheaperinference",
    baseUrl: "https://api.cheaperinference.com/v1/chat/completions",
    validateUrl: "https://api.cheaperinference.com/v1/models",
    responsesUrl: "https://api.cheaperinference.com/v1/responses",
    auth: {
      combined: true,
      header: "Authorization",
      scheme: "bearer",
    },
  },
  models: [
    {
      id: "aion-labs.aion-2-0",
      name: "Aion 2.0",
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "claude-fable-5",
      name: "Claude Fable 5",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "claude-haiku-4.5",
      name: "Claude Haiku 4.5",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "claude-opus-4-7-fast",
      name: "Claude Opus 4.7 Fast",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "claude-opus-4-8-fast",
      name: "Claude Opus 4.8 Fast",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.5",
      name: "Claude Opus 4.5",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.6",
      name: "Claude Opus 4.6",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.7",
      name: "Claude Opus 4.7",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "claude-opus-4.8",
      name: "Claude Opus 4.8",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "claude-opus-5",
      name: "Claude Opus 5",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "claude-opus-5-fast",
      name: "Claude Opus 5 Fast",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "claude-sonnet-4.5",
      name: "Claude Sonnet 4.5",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "claude-sonnet-4.6",
      name: "Claude Sonnet 4.6",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "claude-sonnet-5",
      name: "Claude Sonnet 5",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "deepseek-v4-flash",
      name: "DeepSeek V4 Flash",
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "deepseek-v4-pro",
      name: "DeepSeek V4 Pro",
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "gemini-2.5-flash",
      name: "Gemini 2.5 Flash",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "gemini-3.7-flash",
      name: "Gemini 3.7 Flash",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "gemini-3-flash-preview",
      name: "Gemini 3 Flash Preview",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "gemini-3.1-flash-lite",
      name: "Gemini 3.1 Flash Lite",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "gemini-3.1-pro",
      name: "Gemini 3.1 Pro",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "gemini-3.1-pro-preview",
      name: "Gemini 3.1 Pro Preview",
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "glm-4.5",
      name: "GLM-4.5",
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "glm-4.5-air",
      name: "GLM-4.5 Air",
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "glm-4.6",
      name: "GLM-4.6",
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "glm-4.7",
      name: "GLM-4.7",
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "glm-5",
      name: "GLM-5",
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "glm-5.1",
      name: "GLM-5.1",
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "glm-5.2",
      name: "GLM-5.2",
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "google/gemini-3.5-flash-lite",
      name: "Gemini 3.5 Flash Lite",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "gpt-5.4",
      name: "GPT-5.4",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
      targetFormat: "openai-responses",
    },
    {
      id: "gpt-5.4-mini",
      name: "GPT-5.4 Mini",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
      targetFormat: "openai-responses",
    },
    {
      id: "gpt-5.5",
      name: "GPT-5.5",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
      targetFormat: "openai-responses",
    },
    {
      id: "gpt-5.6-luna",
      name: "GPT-5.6 Luna",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
      targetFormat: "openai-responses",
    },
    {
      id: "gpt-5.6-sol",
      name: "GPT-5.6 Sol",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
      targetFormat: "openai-responses",
    },
    {
      id: "gpt-5.6-terra",
      name: "GPT-5.6 Terra",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
      targetFormat: "openai-responses",
    },
    {
      id: "grok-4.5",
      name: "Grok 4.5",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "kimi-k3",
      name: "Kimi K3",
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "minimax-m2.7",
      name: "MiniMax M2.7",
      supportsReasoning: true,
      toolCalling: true,
    },
  ],
};
