export default {
  id: "cursor-api",
  alias: "cua",
  display: {
    name: "Cursor API",
    icon: "code",
    color: "#6C5CE7",
    textIcon: "CA",
    website: "https://cursor.com",
  },
  category: "apikey",
  authType: "apikey",
  transport: {
    format: "cursor",
    executor: "cursor-api",
    baseUrl: "https://api2.cursor.sh",
    headers: {
      "connect-accept-encoding": "gzip",
      "connect-protocol-version": "1",
      "Content-Type": "application/connect+proto",
      "User-Agent": "Cursor/3.9",
    },
    cliVersion: "3.9",
    chatPath: "/aiserver.v1.ChatService/StreamUnifiedChatWithTools",
    auth: {
      combined: true,
      header: "Authorization",
      scheme: "bearer",
    },
  },
  models: [
    {
      id: "auto",
      name: "Auto (current, default)",
      contextLength: 200000,
    },
    {
      id: "auto-cost",
      name: "Auto (cost)",
      contextLength: 200000,
    },
    {
      id: "auto-balance",
      name: "Auto (balance)",
      contextLength: 200000,
    },
    {
      id: "auto-intelligence",
      name: "Auto (intelligence)",
      contextLength: 200000,
    },
    {
      id: "composer-2",
      name: "Composer 2",
      contextLength: 200000,
    },
    {
      id: "composer-2-fast",
      name: "Composer 2 Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-low-fast",
      name: "GPT 5.4 Low Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.3-codex-spark-preview-low",
      name: "GPT 5.3 Codex Spark Preview Low",
      contextLength: 200000,
    },
    {
      id: "gpt-5.3-codex-spark-preview",
      name: "GPT 5.3 Codex Spark Preview",
      contextLength: 200000,
    },
    {
      id: "gpt-5.3-codex-spark-preview-high",
      name: "GPT 5.3 Codex Spark Preview High",
      contextLength: 200000,
    },
    {
      id: "gpt-5.3-codex-spark-preview-xhigh",
      name: "GPT 5.3 Codex Spark Preview XHigh",
      contextLength: 200000,
    },
    {
      id: "claude-4.6-opus-high-thinking-fast",
      name: "Claude 4.6 Opus High Thinking Fast",
      scoresAs: "claude-opus-4-6",
      contextLength: 200000,
    },
    {
      id: "claude-4.6-opus-max-thinking-fast",
      name: "Claude 4.6 Opus Max Thinking Fast",
      scoresAs: "claude-opus-4-6",
      contextLength: 200000,
    },
    {
      id: "claude-4.6-sonnet-medium",
      name: "Claude 4.6 Sonnet Medium",
      scoresAs: "claude-sonnet-4-6",
      contextLength: 200000,
    },
    {
      id: "claude-4.6-sonnet-medium-thinking",
      name: "Claude 4.6 Sonnet Medium Thinking",
      scoresAs: "claude-sonnet-4-6",
      contextLength: 200000,
    },
    {
      id: "gemini-3.1-pro",
      name: "Gemini 3.1 Pro",
      contextLength: 200000,
    },
    {
      id: "gemini-3.7-flash",
      name: "Gemini 3.7 Flash",
      contextLength: 200000,
    },
    {
      id: "gemini-3-flash",
      name: "Gemini 3 Flash",
      contextLength: 200000,
    },
    {
      id: "grok-4.6-medium",
      name: "Grok 4.6 Medium",
      contextLength: 200000,
    },
    {
      id: "grok-4.6-fast-medium",
      name: "Grok 4.6 Fast Medium",
      contextLength: 200000,
    },
    {
      id: "grok-4.6-high",
      name: "Grok 4.6 High",
      contextLength: 200000,
    },
    {
      id: "grok-4.6-fast-high",
      name: "Grok 4.6 Fast High",
      contextLength: 200000,
    },
    {
      id: "grok-4.6-xhigh",
      name: "Grok 4.6 XHigh",
      contextLength: 200000,
    },
    {
      id: "grok-4.6-fast-xhigh",
      name: "Grok 4.6 Fast XHigh",
      contextLength: 200000,
    },
    {
      id: "kimi-k3",
      name: "Kimi K3",
      contextLength: 200000,
    },
    {
      id: "kimi-k2.7-code",
      name: "Kimi K2.7 Code",
      contextLength: 200000,
    },
    {
      id: "grok-4.3",
      name: "Grok 4.3",
      contextLength: 200000,
    },
    {
      id: "grok-4.5-medium",
      name: "Grok 4.5 Medium",
      contextLength: 200000,
    },
    {
      id: "grok-4.5-fast-medium",
      name: "Grok 4.5 Fast Medium",
      contextLength: 200000,
    },
    {
      id: "grok-4.5-high",
      name: "Grok 4.5 High",
      contextLength: 200000,
    },
    {
      id: "grok-4.5-fast-high",
      name: "Grok 4.5 Fast High",
      contextLength: 200000,
    },
    {
      id: "grok-4.5-xhigh",
      name: "Grok 4.5 XHigh",
      contextLength: 200000,
    },
    {
      id: "grok-4.5-fast-xhigh",
      name: "Grok 4.5 Fast XHigh",
      contextLength: 200000,
    },
    {
      id: "kimi-k2.5",
      name: "Kimi K2.5",
      contextLength: 200000,
    },
    {
      id: "gpt-5.3-codex-low",
      name: "Codex 5.3 Low",
      contextLength: 200000,
    },
    {
      id: "gpt-5.3-codex-low-fast",
      name: "Codex 5.3 Low Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.3-codex",
      name: "Codex 5.3",
      contextLength: 200000,
    },
    {
      id: "gpt-5.3-codex-fast",
      name: "Codex 5.3 Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.3-codex-high",
      name: "Codex 5.3 High",
      contextLength: 200000,
    },
    {
      id: "gpt-5.3-codex-high-fast",
      name: "Codex 5.3 High Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.3-codex-xhigh",
      name: "Codex 5.3 Extra High",
      contextLength: 200000,
    },
    {
      id: "gpt-5.3-codex-xhigh-fast",
      name: "Codex 5.3 Extra High Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.2",
      name: "GPT-5.2",
      contextLength: 200000,
    },
    {
      id: "cursor-grok-4.5-high",
      name: "Cursor Grok 4.5",
      contextLength: 200000,
    },
    {
      id: "cursor-grok-4.5-high-fast",
      name: "Cursor Grok 4.5 Fast",
      contextLength: 200000,
    },
    {
      id: "composer-2.5",
      name: "Composer 2.5",
      contextLength: 200000,
    },
    {
      id: "claude-opus-5-thinking-high",
      name: "Opus 5 1M Thinking",
      contextLength: 200000,
    },
    {
      id: "claude-opus-5-thinking-high-fast",
      name: "Opus 5 1M Thinking Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-5-thinking-xhigh",
      name: "Opus 5 1M Extra High Thinking",
      contextLength: 200000,
    },
    {
      id: "claude-opus-5-thinking-xhigh-fast",
      name: "Opus 5 1M Extra High Thinking Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-thinking-high",
      name: "Opus 4.8 1M Thinking",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-thinking-high-fast",
      name: "Opus 4.8 1M Thinking Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-sol-high",
      name: "GPT-5.6 Sol 1M High",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-sol-high-fast",
      name: "GPT-5.6 Sol High Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-sol-xhigh",
      name: "GPT-5.6 Sol 1M Extra High",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-sol-xhigh-fast",
      name: "GPT-5.6 Sol Extra High Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.5-high",
      name: "GPT-5.5 1M High",
      contextLength: 200000,
    },
    {
      id: "gpt-5.5-high-fast",
      name: "GPT-5.5 High Fast",
      contextLength: 200000,
    },
    {
      id: "claude-fable-5-thinking-high",
      name: "Fable 5 1M Thinking (NO ZDR)",
      contextLength: 200000,
    },
    {
      id: "claude-fable-5-thinking-xhigh",
      name: "Fable 5 1M Extra High Thinking (NO ZDR)",
      contextLength: 200000,
    },
    {
      id: "claude-sonnet-5-thinking-high",
      name: "Sonnet 5 1M Thinking",
      contextLength: 200000,
    },
    {
      id: "claude-sonnet-5-thinking-xhigh",
      name: "Sonnet 5 1M Extra High Thinking",
      contextLength: 200000,
    },
    {
      id: "kimi-k3-high",
      name: "Kimi K3 High",
      contextLength: 200000,
    },
    {
      id: "cursor-grok-4.5-low",
      name: "Cursor Grok 4.5 Low",
      contextLength: 200000,
    },
    {
      id: "cursor-grok-4.5-low-fast",
      name: "Cursor Grok 4.5 Low Fast",
      contextLength: 200000,
    },
    {
      id: "cursor-grok-4.5-medium",
      name: "Cursor Grok 4.5 Medium",
      contextLength: 200000,
    },
    {
      id: "cursor-grok-4.5-medium-fast",
      name: "Cursor Grok 4.5 Medium Fast",
      contextLength: 200000,
    },
    {
      id: "composer-2.5-fast",
      name: "Composer 2.5 Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-5-low",
      name: "Opus 5 1M Low",
      contextLength: 200000,
    },
    {
      id: "claude-opus-5-low-fast",
      name: "Opus 5 1M Low Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-5-medium",
      name: "Opus 5 1M Medium",
      contextLength: 200000,
    },
    {
      id: "claude-opus-5-medium-fast",
      name: "Opus 5 1M Medium Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-5-high",
      name: "Opus 5 1M",
      contextLength: 200000,
    },
    {
      id: "claude-opus-5-high-fast",
      name: "Opus 5 1M Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-5-thinking-low",
      name: "Opus 5 1M Low Thinking",
      contextLength: 200000,
    },
    {
      id: "claude-opus-5-thinking-low-fast",
      name: "Opus 5 1M Low Thinking Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-5-thinking-medium",
      name: "Opus 5 1M Medium Thinking",
      contextLength: 200000,
    },
    {
      id: "claude-opus-5-thinking-medium-fast",
      name: "Opus 5 1M Medium Thinking Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-5-thinking-max",
      name: "Opus 5 1M Max Thinking",
      contextLength: 200000,
    },
    {
      id: "claude-opus-5-thinking-max-fast",
      name: "Opus 5 1M Max Thinking Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-low",
      name: "Opus 4.8 1M Low",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-low-fast",
      name: "Opus 4.8 1M Low Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-medium",
      name: "Opus 4.8 1M Medium",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-medium-fast",
      name: "Opus 4.8 1M Medium Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-high",
      name: "Opus 4.8 1M",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-high-fast",
      name: "Opus 4.8 1M Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-xhigh",
      name: "Opus 4.8 1M Extra High",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-xhigh-fast",
      name: "Opus 4.8 1M Extra High Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-max",
      name: "Opus 4.8 1M Max",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-max-fast",
      name: "Opus 4.8 1M Max Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-thinking-low",
      name: "Opus 4.8 1M Low Thinking",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-thinking-low-fast",
      name: "Opus 4.8 1M Low Thinking Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-thinking-medium",
      name: "Opus 4.8 1M Medium Thinking",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-thinking-medium-fast",
      name: "Opus 4.8 1M Medium Thinking Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-thinking-xhigh",
      name: "Opus 4.8 1M Extra High Thinking",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-thinking-xhigh-fast",
      name: "Opus 4.8 1M Extra High Thinking Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-thinking-max",
      name: "Opus 4.8 1M Max Thinking",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-8-thinking-max-fast",
      name: "Opus 4.8 1M Max Thinking Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-sol-none",
      name: "GPT-5.6 Sol 1M None",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-sol-none-fast",
      name: "GPT-5.6 Sol None Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-sol-low",
      name: "GPT-5.6 Sol 1M Low",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-sol-low-fast",
      name: "GPT-5.6 Sol Low Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-sol-medium",
      name: "GPT-5.6 Sol 1M",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-sol-medium-fast",
      name: "GPT-5.6 Sol Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-sol-max",
      name: "GPT-5.6 Sol 1M Max",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-sol-max-fast",
      name: "GPT-5.6 Sol Max Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.5-none",
      name: "GPT-5.5 1M None",
      contextLength: 200000,
    },
    {
      id: "gpt-5.5-none-fast",
      name: "GPT-5.5 None Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.5-low",
      name: "GPT-5.5 1M Low",
      contextLength: 200000,
    },
    {
      id: "gpt-5.5-low-fast",
      name: "GPT-5.5 Low Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.5-medium",
      name: "GPT-5.5 1M",
      contextLength: 200000,
    },
    {
      id: "gpt-5.5-medium-fast",
      name: "GPT-5.5 Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.5-extra-high",
      name: "GPT-5.5 1M Extra High",
      contextLength: 200000,
    },
    {
      id: "gpt-5.5-extra-high-fast",
      name: "GPT-5.5 Extra High Fast",
      contextLength: 200000,
    },
    {
      id: "claude-fable-5-low",
      name: "Fable 5 1M Low (NO ZDR)",
      contextLength: 200000,
    },
    {
      id: "claude-fable-5-medium",
      name: "Fable 5 1M Medium (NO ZDR)",
      contextLength: 200000,
    },
    {
      id: "claude-fable-5-high",
      name: "Fable 5 1M (NO ZDR)",
      contextLength: 200000,
    },
    {
      id: "claude-fable-5-xhigh",
      name: "Fable 5 1M Extra High (NO ZDR)",
      contextLength: 200000,
    },
    {
      id: "claude-fable-5-max",
      name: "Fable 5 1M Max (NO ZDR)",
      contextLength: 200000,
    },
    {
      id: "claude-fable-5-thinking-low",
      name: "Fable 5 1M Low Thinking (NO ZDR)",
      contextLength: 200000,
    },
    {
      id: "claude-fable-5-thinking-medium",
      name: "Fable 5 1M Medium Thinking (NO ZDR)",
      contextLength: 200000,
    },
    {
      id: "claude-fable-5-thinking-max",
      name: "Fable 5 1M Max Thinking (NO ZDR)",
      contextLength: 200000,
    },
    {
      id: "claude-sonnet-5-low",
      name: "Sonnet 5 1M Low",
      contextLength: 200000,
    },
    {
      id: "claude-sonnet-5-medium",
      name: "Sonnet 5 1M Medium",
      contextLength: 200000,
    },
    {
      id: "claude-sonnet-5-high",
      name: "Sonnet 5 1M",
      contextLength: 200000,
    },
    {
      id: "claude-sonnet-5-xhigh",
      name: "Sonnet 5 1M Extra High",
      contextLength: 200000,
    },
    {
      id: "claude-sonnet-5-max",
      name: "Sonnet 5 1M Max",
      contextLength: 200000,
    },
    {
      id: "claude-sonnet-5-thinking-low",
      name: "Sonnet 5 1M Low Thinking",
      contextLength: 200000,
    },
    {
      id: "claude-sonnet-5-thinking-medium",
      name: "Sonnet 5 1M Medium Thinking",
      contextLength: 200000,
    },
    {
      id: "claude-sonnet-5-thinking-max",
      name: "Sonnet 5 1M Max Thinking",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-terra-none",
      name: "GPT-5.6 Terra 1M None",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-terra-none-fast",
      name: "GPT-5.6 Terra None Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-terra-low",
      name: "GPT-5.6 Terra 1M Low",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-terra-low-fast",
      name: "GPT-5.6 Terra Low Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-terra-medium",
      name: "GPT-5.6 Terra 1M",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-terra-medium-fast",
      name: "GPT-5.6 Terra Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-terra-high",
      name: "GPT-5.6 Terra 1M High",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-terra-high-fast",
      name: "GPT-5.6 Terra High Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-terra-xhigh",
      name: "GPT-5.6 Terra 1M Extra High",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-terra-xhigh-fast",
      name: "GPT-5.6 Terra Extra High Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-terra-max",
      name: "GPT-5.6 Terra 1M Max",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-terra-max-fast",
      name: "GPT-5.6 Terra Max Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-low",
      name: "Opus 4.7 1M Low",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-low-fast",
      name: "Opus 4.7 1M Low Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-medium",
      name: "Opus 4.7 1M Medium",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-medium-fast",
      name: "Opus 4.7 1M Medium Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-high",
      name: "Opus 4.7 1M High",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-high-fast",
      name: "Opus 4.7 1M High Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-xhigh",
      name: "Opus 4.7 1M",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-xhigh-fast",
      name: "Opus 4.7 1M Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-max",
      name: "Opus 4.7 1M Max",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-max-fast",
      name: "Opus 4.7 1M Max Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-thinking-low",
      name: "Opus 4.7 1M Low Thinking",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-thinking-low-fast",
      name: "Opus 4.7 1M Low Thinking Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-thinking-medium",
      name: "Opus 4.7 1M Medium Thinking",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-thinking-medium-fast",
      name: "Opus 4.7 1M Medium Thinking Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-thinking-high",
      name: "Opus 4.7 1M High Thinking",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-thinking-high-fast",
      name: "Opus 4.7 1M High Thinking Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-thinking-xhigh",
      name: "Opus 4.7 1M Thinking",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-thinking-xhigh-fast",
      name: "Opus 4.7 1M Thinking Fast",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-thinking-max",
      name: "Opus 4.7 1M Max Thinking",
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-7-thinking-max-fast",
      name: "Opus 4.7 1M Max Thinking Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-low",
      name: "GPT-5.4 1M Low",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-medium",
      name: "GPT-5.4 1M",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-medium-fast",
      name: "GPT-5.4 Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-high",
      name: "GPT-5.4 1M High",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-high-fast",
      name: "GPT-5.4 High Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-xhigh",
      name: "GPT-5.4 1M Extra High",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-xhigh-fast",
      name: "GPT-5.4 Extra High Fast",
      contextLength: 200000,
    },
    {
      id: "claude-4.6-opus-high",
      name: "Opus 4.6 1M",
      scoresAs: "claude-opus-4-6",
      contextLength: 200000,
    },
    {
      id: "claude-4.6-opus-max",
      name: "Opus 4.6 1M Max",
      scoresAs: "claude-opus-4-6",
      contextLength: 200000,
    },
    {
      id: "claude-4.6-opus-high-thinking",
      name: "Opus 4.6 1M Thinking",
      scoresAs: "claude-opus-4-6",
      contextLength: 200000,
    },
    {
      id: "claude-4.6-opus-max-thinking",
      name: "Opus 4.6 1M Max Thinking",
      scoresAs: "claude-opus-4-6",
      contextLength: 200000,
    },
    {
      id: "claude-4.5-opus-high",
      name: "Opus 4.5",
      scoresAs: "claude-opus-4-5",
      contextLength: 200000,
    },
    {
      id: "claude-4.5-opus-high-thinking",
      name: "Opus 4.5 Thinking",
      scoresAs: "claude-opus-4-5",
      contextLength: 200000,
    },
    {
      id: "gpt-5.2-low",
      name: "GPT-5.2 Low",
      contextLength: 200000,
    },
    {
      id: "gpt-5.2-low-fast",
      name: "GPT-5.2 Low Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.2-fast",
      name: "GPT-5.2 Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.2-high",
      name: "GPT-5.2 High",
      contextLength: 200000,
    },
    {
      id: "gpt-5.2-high-fast",
      name: "GPT-5.2 High Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.2-xhigh",
      name: "GPT-5.2 Extra High",
      contextLength: 200000,
    },
    {
      id: "gpt-5.2-xhigh-fast",
      name: "GPT-5.2 Extra High Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-luna-none",
      name: "GPT-5.6 Luna 1M None",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-luna-none-fast",
      name: "GPT-5.6 Luna None Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-luna-low",
      name: "GPT-5.6 Luna 1M Low",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-luna-low-fast",
      name: "GPT-5.6 Luna Low Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-luna-medium",
      name: "GPT-5.6 Luna 1M",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-luna-medium-fast",
      name: "GPT-5.6 Luna Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-luna-high",
      name: "GPT-5.6 Luna 1M High",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-luna-high-fast",
      name: "GPT-5.6 Luna High Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-luna-xhigh",
      name: "GPT-5.6 Luna 1M Extra High",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-luna-xhigh-fast",
      name: "GPT-5.6 Luna Extra High Fast",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-luna-max",
      name: "GPT-5.6 Luna 1M Max",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-luna-max-fast",
      name: "GPT-5.6 Luna Max Fast",
      contextLength: 200000,
    },
    {
      id: "gemini-3.6-flash-minimal",
      name: "Gemini 3.6 Flash Minimal",
      contextLength: 200000,
    },
    {
      id: "gemini-3.6-flash-low",
      name: "Gemini 3.6 Flash Low",
      contextLength: 200000,
    },
    {
      id: "gemini-3.6-flash-medium",
      name: "Gemini 3.6 Flash Medium",
      contextLength: 200000,
    },
    {
      id: "gemini-3.6-flash-high",
      name: "Gemini 3.6 Flash",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-mini-none",
      name: "GPT-5.4 Mini None",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-mini-low",
      name: "GPT-5.4 Mini Low",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-mini-medium",
      name: "GPT-5.4 Mini",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-mini-high",
      name: "GPT-5.4 Mini High",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-mini-xhigh",
      name: "GPT-5.4 Mini Extra High",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-nano-none",
      name: "GPT-5.4 Nano None",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-nano-low",
      name: "GPT-5.4 Nano Low",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-nano-medium",
      name: "GPT-5.4 Nano",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-nano-high",
      name: "GPT-5.4 Nano High",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-nano-xhigh",
      name: "GPT-5.4 Nano Extra High",
      contextLength: 200000,
    },
    {
      id: "claude-4.5-sonnet",
      name: "Sonnet 4.5",
      scoresAs: "claude-sonnet-4-5",
      contextLength: 200000,
    },
    {
      id: "claude-4.5-sonnet-thinking",
      name: "Sonnet 4.5 Thinking",
      scoresAs: "claude-sonnet-4-5",
      contextLength: 200000,
    },
    {
      id: "gpt-5.1-low",
      name: "GPT-5.1 Low",
      contextLength: 200000,
    },
    {
      id: "gpt-5.1",
      name: "GPT-5.1",
      contextLength: 200000,
    },
    {
      id: "gpt-5.1-high",
      name: "GPT-5.1 High",
      contextLength: 200000,
    },
    {
      id: "claude-4-sonnet",
      name: "Sonnet 4",
      scoresAs: "claude-sonnet-4",
      contextLength: 200000,
    },
    {
      id: "claude-4-sonnet-thinking",
      name: "Sonnet 4 Thinking",
      scoresAs: "claude-sonnet-4",
      contextLength: 200000,
    },
    {
      id: "gpt-5-mini",
      name: "GPT-5 Mini",
      contextLength: 200000,
    },
    {
      id: "kimi-k3-low",
      name: "Kimi K3 Low",
      contextLength: 200000,
    },
    {
      id: "kimi-k3-max",
      name: "Kimi K3",
      contextLength: 200000,
    },
    {
      id: "glm-5.2-high",
      name: "GLM 5.2",
      contextLength: 200000,
    },
    {
      id: "glm-5.2-max",
      name: "GLM 5.2 Max",
      contextLength: 200000,
    },
  ],
};
