export default {
  id: "ghe-copilot",
  alias: "ghe-copilot",
  display: {
    name: "GitHub Enterprise Copilot",
    icon: "code",
    color: "#24292F",
    textIcon: "GHE",
    website: "https://github.com",
  },
  category: "oauth",
  authType: "oauth",
  hasOAuth: true,
  transport: {
    format: "openai",
    executor: "ghe-copilot",
    baseUrl: "https://api.githubcopilot.com/chat/completions",
    validateUrl: "https://api.githubcopilot.com/models",
    responsesUrl: "https://api.githubcopilot.com/responses",
    messagesUrl: "https://api.githubcopilot.com/v1/messages",
    headers: {
      "copilot-integration-id": "copilot-developer-cli",
      "editor-version": "copilot/1.0.81-6",
      "user-agent": "copilot/1.0.81-6",
      "openai-intent": "conversation-agent",
      "x-interaction-type": "conversation-user",
      "copilot-harness-id": "copilot-sdk",
      "x-github-api-version": "2026-08-01",
      "x-client-machine-id": "51a67209-0294-43f9-b913-5e7e88fb4d85",
      "X-Initiator": "user",
      Accept: "application/json",
      "Content-Type": "application/json",
    },
    forceStream: true,
    auth: {
      combined: true,
      header: "Authorization",
      scheme: "bearer",
    },
  },
  oauth: {
    clientIdEnv: "GITHUB_OAUTH_CLIENT_ID",
    clientId: "Iv1.b507a08c87ecfe98",
  },
  models: [
    {
      id: "claude-fable-5",
      name: "Claude Fable 5",
      contextLength: 1000000,
      maxOutputTokens: 64000,
    },
    {
      id: "claude-opus-5",
      name: "Claude Opus 5",
      contextLength: 1000000,
      maxOutputTokens: 64000,
      unsupportedParams: [
        "temperature",
        "top_p",
        "top_k",
      ],
    },
    {
      id: "claude-opus-4.8-fast",
      name: "Claude Opus 4.8 (fast mode)",
      contextLength: 1000000,
      maxOutputTokens: 64000,
      unsupportedParams: [
        "temperature",
        "top_p",
        "top_k",
      ],
    },
    {
      id: "claude-opus-4.8",
      name: "Claude Opus 4.8",
      contextLength: 1000000,
      maxOutputTokens: 64000,
      unsupportedParams: [
        "temperature",
        "top_p",
        "top_k",
      ],
    },
    {
      id: "claude-opus-4.7",
      name: "Claude Opus 4.7",
      contextLength: 1000000,
      maxOutputTokens: 64000,
    },
    {
      id: "claude-sonnet-4.6",
      name: "Claude Sonnet 4.6",
      contextLength: 1000000,
      maxOutputTokens: 64000,
    },
    {
      id: "claude-opus-4.5",
      name: "Claude Opus 4.5",
      contextLength: 200000,
      maxOutputTokens: 32000,
    },
    {
      id: "claude-sonnet-5",
      name: "Claude Sonnet 5",
      contextLength: 1000000,
      maxOutputTokens: 64000,
    },
    {
      id: "claude-sonnet-4.5",
      name: "Claude Sonnet 4.5",
      contextLength: 200000,
      maxOutputTokens: 32000,
    },
    {
      id: "claude-haiku-4.5",
      name: "Claude Haiku 4.5",
      contextLength: 200000,
      maxOutputTokens: 32000,
    },
    {
      id: "gemini-3.1-pro-preview",
      name: "Gemini 3.1 Pro",
      contextLength: 1000000,
      maxOutputTokens: 64000,
    },
    {
      id: "gemini-3.7-flash",
      name: "Gemini 3.7 Flash",
      contextLength: 1000000,
      maxOutputTokens: 64000,
    },
    {
      id: "gpt-5.6-sol",
      name: "GPT-5.6 Sol",
      targetFormat: "openai-responses",
      maxOutputTokens: 128000,
      contextLength: 128000,
    },
    {
      id: "gpt-5.6-terra",
      name: "GPT-5.6 Terra",
      targetFormat: "openai-responses",
      maxOutputTokens: 128000,
      contextLength: 128000,
    },
    {
      id: "gpt-5.6-luna",
      name: "GPT-5.6 Luna",
      targetFormat: "openai-responses",
      maxOutputTokens: 128000,
      contextLength: 128000,
    },
    {
      id: "gpt-5.5",
      name: "GPT-5.5",
      targetFormat: "openai-responses",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      supportsXHighEffort: true,
      contextLength: 1050000,
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5.4",
      name: "GPT-5.4",
      targetFormat: "openai-responses",
      supportsXHighEffort: true,
      contextLength: 1050000,
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5.4-mini",
      name: "GPT-5.4 mini",
      targetFormat: "openai-responses",
      contextLength: 400000,
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5.3-codex",
      name: "GPT-5.3-Codex",
      targetFormat: "openai-responses",
      contextLength: 400000,
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5-mini",
      name: "GPT-5 mini",
      targetFormat: "openai-responses",
      contextLength: 264000,
      maxOutputTokens: 64000,
    },
    {
      id: "gpt-4o-2024-11-20",
      name: "GPT-4o",
      contextLength: 128000,
      maxOutputTokens: 16384,
    },
    {
      id: "gpt-4o-mini",
      name: "GPT-4o mini",
      contextLength: 128000,
      maxOutputTokens: 4096,
    },
    {
      id: "gpt-4-0125-preview",
      name: "GPT 4 Turbo",
      contextLength: 128000,
      maxOutputTokens: 4096,
    },
    {
      id: "kimi-k2.7-code",
      name: "Kimi K2.7 Code",
      contextLength: 256000,
      maxOutputTokens: 32000,
    },
    {
      id: "mai-code-1-flash",
      name: "MAI-Code-1-Flash",
      targetFormat: "openai-responses",
      contextLength: 256000,
      maxOutputTokens: 128000,
    },
    {
      id: "oswe-vscode-prime",
      name: "Raptor mini",
      targetFormat: "openai-responses",
      contextLength: 264000,
      maxOutputTokens: 64000,
    },
  ],
};
