export default {
  id: "glmt",
  alias: "glmt",
  display: {
    name: "GLM-T",
    icon: "bolt",
    color: "#3859FF",
    textIcon: "GLMT",
    website: "https://z.ai",
  },
  category: "apikey",
  authType: "apikey",
  transport: {
    format: "openai",
    executor: "glm",
    baseUrl: "https://api.z.ai/api/coding/paas/v4/chat/completions",
    validateUrl: "https://api.z.ai/api/coding/paas/v4/models",
    timeoutMs: 900000,
    auth: {
      combined: true,
      header: "Authorization",
      scheme: "bearer",
    },
  },
  models: [
    {
      id: "glm-5.3",
      name: "GLM 5.3",
      contextLength: 1000000,
      maxOutputTokens: 131072,
      toolCalling: true,
      supportsReasoning: true,
      supportedThinkingEfforts: [
        "low",
        "high",
        "max",
      ],
    },
    {
      id: "glm-5.3-high",
      name: "GLM 5.3 High",
      contextLength: 1000000,
      maxOutputTokens: 131072,
      toolCalling: true,
      supportsReasoning: true,
      supportedThinkingEfforts: [
        "high",
      ],
    },
    {
      id: "glm-5.3-low",
      name: "GLM 5.3 Low",
      contextLength: 1000000,
      maxOutputTokens: 131072,
      toolCalling: true,
      supportsReasoning: true,
      supportedThinkingEfforts: [
        "low",
      ],
    },
    {
      id: "glm-5.3-max",
      name: "GLM 5.3 Max",
      contextLength: 1000000,
      maxOutputTokens: 131072,
      toolCalling: true,
      supportsReasoning: true,
      supportedThinkingEfforts: [
        "max",
      ],
    },
    {
      id: "glm-5.2",
      name: "GLM 5.2",
      contextLength: 1000000,
      maxOutputTokens: 131072,
      toolCalling: true,
      supportsReasoning: true,
      supportedThinkingEfforts: [
        "high",
        "max",
      ],
    },
    {
      id: "glm-5.2-high",
      name: "GLM 5.2 High",
      contextLength: 1000000,
      maxOutputTokens: 131072,
      toolCalling: true,
      supportsReasoning: true,
      supportedThinkingEfforts: [
        "high",
      ],
    },
    {
      id: "glm-5.2-max",
      name: "GLM 5.2 Max",
      contextLength: 1000000,
      maxOutputTokens: 131072,
      toolCalling: true,
      supportsReasoning: true,
      supportedThinkingEfforts: [
        "max",
      ],
    },
    {
      id: "glm-5.1",
      name: "GLM 5.1",
      contextLength: 204800,
      maxOutputTokens: 131072,
      toolCalling: true,
      supportsReasoning: true,
      supportedThinkingEfforts: [],
    },
    {
      id: "glm-5",
      name: "GLM 5",
      contextLength: 200000,
      maxOutputTokens: 131072,
      toolCalling: true,
      supportsReasoning: true,
      supportedThinkingEfforts: [],
    },
    {
      id: "glm-5-turbo",
      name: "GLM 5 Turbo",
      contextLength: 200000,
      maxOutputTokens: 131072,
      toolCalling: true,
      supportsReasoning: true,
      supportedThinkingEfforts: [],
    },
    {
      id: "glm-4.7-flash",
      name: "GLM 4.7 Flash",
      contextLength: 200000,
      maxOutputTokens: 131072,
      toolCalling: true,
      supportsReasoning: true,
      supportedThinkingEfforts: [],
    },
    {
      id: "glm-4.7",
      name: "GLM 4.7",
      contextLength: 200000,
      maxOutputTokens: 131072,
      toolCalling: true,
      supportsReasoning: true,
      supportedThinkingEfforts: [],
    },
    {
      id: "glm-4.6v",
      name: "GLM 4.6V (Vision)",
      contextLength: 128000,
      maxOutputTokens: 32768,
      toolCalling: true,
      supportsReasoning: true,
      supportedThinkingEfforts: [],
      supportsVision: true,
    },
    {
      id: "glm-4.6",
      name: "GLM 4.6",
      contextLength: 200000,
      maxOutputTokens: 32768,
      toolCalling: true,
      supportsReasoning: true,
      supportedThinkingEfforts: [],
    },
    {
      id: "glm-4.5v",
      name: "GLM 4.5V (Vision)",
      contextLength: 16000,
      maxOutputTokens: 32768,
      toolCalling: true,
      supportsReasoning: true,
      supportedThinkingEfforts: [],
      supportsVision: true,
    },
    {
      id: "glm-4.5",
      name: "GLM 4.5",
      contextLength: 128000,
      maxOutputTokens: 32768,
      toolCalling: true,
      supportsReasoning: true,
      supportedThinkingEfforts: [],
    },
    {
      id: "glm-4.5-air",
      name: "GLM 4.5 Air",
      contextLength: 128000,
      maxOutputTokens: 32768,
      toolCalling: true,
      supportsReasoning: true,
      supportedThinkingEfforts: [],
    },
  ],
};
