export default {
  id: "moonshot",
  alias: "moonshot",
  display: {
    name: "Moonshot",
    icon: "bolt",
    color: "#22C55E",
    textIcon: "MS",
    website: "https://platform.moonshot.ai",
  },
  category: "apikey",
  authType: "apikey",
  transport: {
    format: "openai",
    executor: "moonshot",
    baseUrl: "https://api.moonshot.ai/v1/chat/completions",
    validateUrl: "https://api.moonshot.ai/v1/models",
    auth: {
      combined: true,
      header: "Authorization",
      scheme: "bearer",
    },
  },
  models: [
    {
      id: "kimi-k3",
      name: "Kimi K3",
      contextLength: 1048576,
      maxOutputTokens: 1048576,
      supportsVision: true,
      supportsReasoning: true,
      supportsXHighEffort: false,
      toolCalling: true,
      interleavedField: "reasoning_content",
      unsupportedParams: [
        "temperature",
        "top_p",
        "frequency_penalty",
        "presence_penalty",
        "logprobs",
        "top_logprobs",
        "n",
      ],
    },
    {
      id: "kimi-k2.7-code",
      name: "Kimi K2.7 Code",
      contextLength: 262144,
      maxOutputTokens: 262144,
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
      interleavedField: "reasoning_content",
      unsupportedParams: [
        "temperature",
        "top_p",
        "frequency_penalty",
        "presence_penalty",
        "logprobs",
        "top_logprobs",
        "n",
      ],
    },
    {
      id: "kimi-k2.7-code-highspeed",
      name: "Kimi K2.7 Code (High Speed)",
      contextLength: 262144,
      maxOutputTokens: 262144,
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
      interleavedField: "reasoning_content",
      unsupportedParams: [
        "temperature",
        "top_p",
        "frequency_penalty",
        "presence_penalty",
        "logprobs",
        "top_logprobs",
        "n",
      ],
    },
    {
      id: "kimi-k2.6",
      name: "Kimi K2.6",
      contextLength: 262144,
      maxOutputTokens: 262144,
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
      interleavedField: "reasoning_content",
      unsupportedParams: [
        "temperature",
        "top_p",
        "frequency_penalty",
        "presence_penalty",
        "logprobs",
        "top_logprobs",
        "n",
      ],
    },
  ],
};
