export default {
  id: "opencode-zen",
  alias: "opencode-zen",
  display: {
    name: "OpenCode Zen",
    icon: "code",
    color: "#0EA5E9",
    textIcon: "OCZ",
  },
  category: "apikey",
  authType: "apikey",
  transport: {
    format: "openai",
    executor: "opencode",
    baseUrl: "https://opencode.ai/zen/v1",
    modelsFetcher: {
      url: "https://opencode.ai/zen/v1/models",
      type: "openai",
    },
    auth: {
      combined: true,
      header: "Authorization",
      scheme: "raw",
    },
  },
  models: [
    {
      id: "big-pickle",
      name: "Big Pickle",
      supportsReasoning: true,
      interleavedField: "reasoning_content",
      contextLength: 200000,
    },
    {
      id: "kimi-k2.7-code",
      name: "Kimi K2.7 Code",
      contextLength: 200000,
    },
    {
      id: "qwen3.5-plus",
      name: "Qwen3.5 Plus",
      targetFormat: "claude",
      supportsVision: false,
      contextLength: 200000,
    },
    {
      id: "qwen3.6-plus",
      name: "Qwen3.6 Plus",
      targetFormat: "claude",
      supportsVision: false,
      supportsReasoning: true,
      supportedThinkingEfforts: [
        "high",
        "max",
      ],
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-sol",
      name: "GPT 5.6 Sol",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-terra",
      name: "GPT 5.6 Terra",
      contextLength: 200000,
    },
    {
      id: "gpt-5.6-luna",
      name: "GPT 5.6 Luna",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4",
      name: "GPT 5.4",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-mini",
      name: "GPT 5.4 Mini",
      contextLength: 200000,
    },
    {
      id: "gpt-5.4-nano",
      name: "GPT 5.4 Nano",
      contextLength: 200000,
    },
    {
      id: "gpt-5.3-codex-spark",
      name: "GPT 5.3 Codex Spark",
      contextLength: 200000,
    },
    {
      id: "gpt-5.1",
      name: "GPT 5.1",
      contextLength: 200000,
    },
    {
      id: "claude-fable-5",
      name: "Claude Fable 5",
      contextLength: 200000,
    },
    {
      id: "claude-opus-5",
      name: "Claude Opus 5",
      contextLength: 200000,
    },
    {
      id: "claude-sonnet-5",
      name: "Claude Sonnet 5",
      contextLength: 200000,
    },
    {
      id: "claude-haiku-4-5",
      name: "Claude Haiku 4.5",
      contextLength: 200000,
    },
    {
      id: "gemini-3.7-flash",
      name: "Gemini 3.7 Flash",
      contextLength: 200000,
    },
    {
      id: "gemini-3.5-flash-lite",
      name: "Gemini 3.5 Flash Lite",
      contextLength: 200000,
    },
    {
      id: "gemini-3.1-pro",
      name: "Gemini 3.1 Pro",
      contextLength: 200000,
    },
    {
      id: "gemini-3-flash",
      name: "Gemini 3 Flash",
      contextLength: 200000,
    },
    {
      id: "grok-build-0.1",
      name: "Grok Build 0.1",
      contextLength: 200000,
    },
    {
      id: "grok-4.6",
      name: "Grok 4.6",
      contextLength: 200000,
    },
    {
      id: "muse-spark-1.2",
      name: "Muse Spark 1.2",
      supportsReasoning: true,
      targetFormat: "openai-responses",
      contextLength: 200000,
    },
    {
      id: "muse-spark-1.2-contributor-free",
      name: "Muse Spark 1.2 Contributor Free",
      supportsReasoning: true,
      targetFormat: "openai-responses",
      contextLength: 200000,
    },
    {
      id: "deepseek-v4-pro",
      name: "DeepSeek V4 Pro",
      supportsReasoning: true,
      supportedThinkingEfforts: [
        "none",
        "low",
        "high",
        "max",
      ],
      contextLength: 200000,
    },
    {
      id: "deepseek-v4-flash",
      name: "DeepSeek V4 Flash",
      supportsReasoning: true,
      supportedThinkingEfforts: [
        "none",
        "low",
        "high",
        "max",
      ],
      contextLength: 200000,
    },
    {
      id: "glm-5.2",
      name: "GLM-5.2",
      supportsReasoning: true,
      supportedThinkingEfforts: [
        "high",
        "max",
      ],
      contextLength: 200000,
    },
    {
      id: "minimax-m3",
      name: "MiniMax M3",
      contextLength: 1048576,
      supportsVision: true,
    },
    {
      id: "kimi-k3",
      name: "Kimi K3",
      supportsReasoning: true,
      supportedThinkingEfforts: [
        "max",
      ],
      contextLength: 200000,
    },
    {
      id: "deepseek-v4-flash-free",
      name: "DeepSeek V4 Flash Free",
      supportsReasoning: true,
      contextLength: 200000,
    },
    {
      id: "mimo-v2.5-free",
      name: "MiMo V2.5 Free",
      contextLength: 200000,
    },
    {
      id: "hy3-free",
      name: "HY3 Free",
      contextLength: 200000,
    },
    {
      id: "nemotron-3-ultra-free",
      name: "Nemotron 3 Ultra Free",
      contextLength: 1000000,
    },
    {
      id: "nemotron-3.5-lightning-free",
      name: "Nemotron 3.5 Lightning Free",
      contextLength: 200000,
    },
    {
      id: "laguna-s-2.1-free",
      name: "Laguna S 2.1 Free",
      contextLength: 200000,
    },
  ],
  passthroughModels: true,
};
