export default {
  id: "qwen-web",
  alias: "qwen-web",
  display: {
    name: "Qwen Web",
    icon: "chat",
    color: "#615CED",
    textIcon: "QW",
    website: "https://chat.qwen.ai",
  },
  category: "apikey",
  authType: "apikey",
  transport: {
    format: "openai",
    executor: "qwen-web",
    baseUrl: "https://chat.qwen.ai/api/v2/chat/completions",
    validateUrl: "https://chat.qwen.ai/api/v2/models",
    auth: {
      combined: true,
      header: "Authorization",
      scheme: "bearer",
    },
  },
  models: [
    {
      id: "qwen3.8-max",
      name: "Qwen3.8 Max",
      toolCalling: false,
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 1000000,
      maxOutputTokens: 131072,
    },
    {
      id: "qwen3.7-max",
      name: "Qwen3.7 Max",
      toolCalling: false,
      supportsReasoning: true,
      supportsVision: false,
      contextLength: 1000000,
      maxOutputTokens: 65536,
    },
    {
      id: "qwen3.7-plus",
      name: "Qwen3.7 Plus",
      toolCalling: false,
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 1000000,
      maxOutputTokens: 65536,
    },
    {
      id: "qwen3.6-plus",
      name: "Qwen3.6 Plus",
      toolCalling: false,
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 1000000,
      maxOutputTokens: 65536,
    },
  ],
};
