// Provider icon paths under /public/providers.
// Providers with a real icon file render it; providers without one render either
// their registry-declared Material Symbol (display.icon) or text icon (display.textIcon),
// so the dashboard never issues a doomed /providers/*.png request (404). GENERATED — do not hand-edit.

const ICON_ALIASES = {
  "perplexity-agent": "perplexity",
  "gitlab-duo": "gitlab",
  "vercel-ai-gateway": "vercel",
};

// Provider ids that genuinely have a file in /public/providers (png/svg/webp/...).
const FILE_ICON_IDS = new Set([
  "360ai",
  "agentrouter",
  "alibaba",
  "alicode",
  "alicode-intl",
  "amp",
  "anthropic",
  "anthropic-m",
  "antigravity",
  "api-airforce",
  "arcee",
  "arcee-ai",
  "assemblyai",
  "auggie",
  "aws",
  "aws-polly",
  "azure",
  "azureai",
  "baichuan",
  "baidu",
  "bailian",
  "baseten",
  "bazaarlink",
  "black-forest-labs",
  "blackbox",
  "bluesminds",
  "brave-search",
  "byteplus",
  "bytez",
  "cartesia",
  "cerebras",
  "charm-hyper",
  "chutes",
  "claude",
  "claude-web",
  "cli-generic",
  "cline",
  "clinepass",
  "cloudflare",
  "cloudflare-ai",
  "codebuddy-cn",
  "codebuddy-intl",
  "codex",
  "cohere",
  "comfyui",
  "commandcode",
  "continue",
  "copilot",
  "coqui",
  "coze",
  "crof",
  "cursor",
  "deepgram",
  "deepinfra",
  "deepseek",
  "deepseek-tui",
  "devin-cli",
  "dgrid",
  "dify",
  "dit",
  "doubao",
  "droid",
  "edge-tts",
  "elevenlabs",
  "exa",
  "factory",
  "fal",
  "fal-ai",
  "featherless",
  "firecrawl",
  "fireworks",
  "freeaiapikey",
  "freemodel-dev",
  "friendli",
  "galadriel",
  "gemini",
  "gemini-cli",
  "github",
  "gitlab",
  "gitlawb",
  "gitlawb-gmi",
  "glm",
  "glm-cn",
  "google",
  "google-pse",
  "google-tts",
  "grok",
  "grok-cli",
  "grok-web",
  "groq",
  "hcnsec",
  "hermes",
  "heroku",
  "huggingchat",
  "huggingface",
  "hyperbolic",
  "ibm",
  "iflow",
  "iflytek",
  "inclusionai",
  "inference",
  "inworld",
  "jcode",
  "jina-ai",
  "jina-reader",
  "kenari",
  "kilo-gateway",
  "kilocode",
  "kimchi",
  "kimi",
  "kimi-coding",
  "kimi-logomark-dark",
  "kimi-logomark-light",
  "kiro",
  "krutrim",
  "lambda",
  "linkup",
  "liquid",
  "llm7",
  "local-device",
  "longcat",
  "meta",
  "metaai",
  "mimo-free",
  "minimax",
  "minimax-cn",
  "mistral",
  "mmf",
  "monsterapi",
  "moonshot",
  "morph",
  "nanobanana",
  "nebius",
  "nomic",
  "novita",
  "nube",
  "nvidia",
  "oai-cc",
  "oai-r",
  "ollama",
  "ollama-local",
  "openadapter",
  "openai",
  "openclaw",
  "opencode",
  "opencode-go",
  "opendesign",
  "openrouter",
  "opper",
  "orcarouter",
  "ovhcloud",
  "perplexity",
  "perplexity-agent",
  "perplexity-web",
  "phind",
  "picoclaw",
  "pioneer",
  "playht",
  "poe",
  "pollinations",
  "poolside",
  "publicai",
  "qoder",
  "qwen",
  "recraft",
  "reka",
  "replicate",
  "requesty",
  "roo",
  "roocode",
  "runway",
  "runwayml",
  "sambanova",
  "sdwebui",
  "searchapi",
  "searxng",
  "sensenova",
  "serper",
  "siliconflow",
  "snowflake",
  "sparkdesk",
  "stability-ai",
  "stepfun",
  "sumopod",
  "suno",
  "t3-web",
  "tavily",
  "tencent",
  "together",
  "tokenrouter",
  "topaz",
  "topazlabs",
  "tortoise",
  "trae",
  "udio",
  "uncloseai",
  "upstage",
  "v0",
  "venice",
  "veoaifree-web",
  "vercel",
  "vercel-ai-gateway",
  "vertex",
  "vertex-partner",
  "vllm",
  "volcengine",
  "volcengine-ark",
  "voyage",
  "voyage-ai",
  "wafer",
  "windsurf",
  "workbuddy",
  "x5lab",
  "xai",
  "xiaomi-mimo",
  "xiaomi-tokenplan",
  "xinference",
  "yi",
  "youcom",
  "yuanbao-web",
  "zed",
  "zed-hosted",
  "zenmux",
  "zenmux-free",
  "zhipu",
]);

const FILE_ICON_EXT = {  "360ai":"svg",  "agentrouter":"png",  "alibaba":"svg",  "alicode":"png",  "alicode-intl":"png",  "amp":"png",  "anthropic":"svg",  "anthropic-m":"png",  "antigravity":"png",  "api-airforce":"png",  "arcee":"svg",  "arcee-ai":"svg",  "assemblyai":"svg",  "auggie":"svg",  "aws":"svg",  "aws-polly":"png",  "azure":"svg",  "azureai":"svg",  "baichuan":"svg",  "baidu":"svg",  "bailian":"svg",  "baseten":"svg",  "bazaarlink":"png",  "black-forest-labs":"png",  "blackbox":"png",  "bluesminds":"svg",  "brave-search":"png",  "byteplus":"png",  "bytez":"svg",  "cartesia":"png",  "cerebras":"svg",  "charm-hyper":"svg",  "chutes":"svg",  "claude":"svg",  "claude-web":"svg",  "cli-generic":"svg",  "cline":"svg",  "clinepass":"png",  "cloudflare":"svg",  "cloudflare-ai":"png",  "codebuddy-cn":"png",  "codebuddy-intl":"png",  "codex":"svg",  "cohere":"svg",  "comfyui":"svg",  "commandcode":"png",  "continue":"svg",  "copilot":"svg",  "coqui":"png",  "coze":"svg",  "crof":"svg",  "cursor":"svg",  "deepgram":"svg",  "deepinfra":"svg",  "deepseek":"svg",  "deepseek-tui":"png",  "devin-cli":"png",  "dgrid":"svg",  "dify":"svg",  "dit":"svg",  "doubao":"svg",  "droid":"png",  "edge-tts":"png",  "elevenlabs":"svg",  "exa":"svg",  "factory":"svg",  "fal":"svg",  "fal-ai":"png",  "featherless":"png",  "firecrawl":"png",  "fireworks":"svg",  "freeaiapikey":"svg",  "freemodel-dev":"svg",  "friendli":"svg",  "galadriel":"svg",  "gemini":"svg",  "gemini-cli":"png",  "github":"png",  "gitlab":"png",  "gitlawb":"svg",  "gitlawb-gmi":"svg",  "glm":"png",  "glm-cn":"png",  "google":"svg",  "google-pse":"png",  "google-tts":"png",  "grok":"svg",  "grok-cli":"png",  "grok-web":"png",  "groq":"svg",  "hcnsec":"svg",  "hermes":"png",  "heroku":"svg",  "huggingchat":"svg",  "huggingface":"svg",  "hyperbolic":"svg",  "ibm":"svg",  "iflow":"png",  "iflytek":"svg",  "inclusionai":"svg",  "inference":"svg",  "inworld":"png",  "jcode":"png",  "jina-ai":"png",  "jina-reader":"png",  "kenari":"svg",  "kilo-gateway":"png",  "kilocode":"png",  "kimchi":"svg",  "kimi":"svg",  "kimi-coding":"png",  "kimi-logomark-dark":"svg",  "kimi-logomark-light":"svg",  "kiro":"svg",  "krutrim":"svg",  "lambda":"svg",  "linkup":"png",  "liquid":"svg",  "llm7":"svg",  "local-device":"png",  "longcat":"svg",  "meta":"svg",  "metaai":"svg",  "mimo-free":"png",  "minimax":"svg",  "minimax-cn":"png",  "mistral":"svg",  "mmf":"png",  "monsterapi":"svg",  "moonshot":"svg",  "morph":"svg",  "nanobanana":"png",  "nebius":"svg",  "nomic":"svg",  "novita":"svg",  "nube":"svg",  "nvidia":"svg",  "oai-cc":"png",  "oai-r":"png",  "ollama":"svg",  "ollama-local":"png",  "openadapter":"svg",  "openai":"svg",  "openclaw":"svg",  "opencode":"png",  "opencode-go":"png",  "opendesign":"png",  "openrouter":"svg",  "opper":"svg",  "orcarouter":"svg",  "ovhcloud":"svg",  "perplexity":"svg",  "perplexity-agent":"png",  "perplexity-web":"png",  "phind":"svg",  "picoclaw":"svg",  "pioneer":"svg",  "playht":"png",  "poe":"svg",  "pollinations":"svg",  "poolside":"svg",  "publicai":"svg",  "qoder":"png",  "qwen":"svg",  "recraft":"svg",  "reka":"png",  "replicate":"svg",  "requesty":"svg",  "roo":"png",  "roocode":"svg",  "runway":"svg",  "runwayml":"png",  "sambanova":"svg",  "sdwebui":"png",  "searchapi":"svg",  "searxng":"png",  "sensenova":"svg",  "serper":"png",  "siliconflow":"png",  "snowflake":"svg",  "sparkdesk":"svg",  "stability-ai":"png",  "stepfun":"svg",  "sumopod":"svg",  "suno":"svg",  "t3-web":"svg",  "tavily":"svg",  "tencent":"svg",  "together":"png",  "tokenrouter":"svg",  "topaz":"png",  "topazlabs":"svg",  "tortoise":"png",  "trae":"svg",  "udio":"svg",  "uncloseai":"svg",  "upstage":"svg",  "v0":"svg",  "venice":"png",  "veoaifree-web":"svg",  "vercel":"svg",  "vercel-ai-gateway":"png",  "vertex":"png",  "vertex-partner":"png",  "vllm":"svg",  "volcengine":"svg",  "volcengine-ark":"png",  "voyage":"svg",  "voyage-ai":"png",  "wafer":"svg",  "windsurf":"svg",  "workbuddy":"png",  "x5lab":"svg",  "xai":"svg",  "xiaomi-mimo":"png",  "xiaomi-tokenplan":"png",  "xinference":"svg",  "yi":"svg",  "youcom":"png",  "yuanbao-web":"svg",  "zed":"png",  "zed-hosted":"svg",  "zenmux":"svg",  "zenmux-free":"svg",  "zhipu":"svg"};

// Material Symbol fallback by provider id (from registry display.icon).
const SYMBOL_ICON_BY_PROVIDER = {
  "360ai": "auto_awesome",
  "9router": "router",
  "adapta-web": "language",
  "adobe-firefly": "image",
  "agy": "smart_toy",
  "ai21": "bolt",
  "aihorde": "groups",
  "ainative": "auto_awesome",
  "aion": "flare",
  "alibaba-cn": "cloud",
  "alims-intl": "cloud",
  "alitp-intl": "cloud",
  "amazon-q": "cloud",
  "anyapi": "hub",
  "arcee-ai": "auto_awesome",
  "auggie": "auto_awesome",
  "auriko": "star",
  "auto": "auto_awesome",
  "azure-ai": "cloud",
  "azure-openai": "cloud",
  "bailian-coding-plan": "code",
  "baseten": "layers",
  "bedrock": "cloud",
  "blackbox-web": "web",
  "bytez": "memory",
  "chat-oripe": "chat",
  "chatanywhere": "forum",
  "chatgpt-web": "chat",
  "chatgpt-web-codex": "terminal",
  "cheaperinference": "savings",
  "chipotle": "local_fire_department",
  "clarifai": "hub",
  "claude-web": "chat",
  "cliproxyapi": "terminal",
  "cloudcode-one": "bolt",
  "cloudflare-playground": "cloud_queue",
  "codestral": "terminal",
  "codex-app-server": "terminal",
  "codex-cloud": "cloud",
  "command-code": "terminal",
  "conol-web": "web",
  "context7": "menu_book",
  "copilot-m365-web": "web",
  "copilot-web": "web",
  "cursor-api": "code",
  "dahl": "nature",
  "dario": "terminal",
  "databricks": "insights",
  "datarobot": "precision_manufacturing",
  "deepai": "bolt",
  "deepinfra": "bolt",
  "deepseek-web": "chat",
  "deepseek-web-with-auto-refresh": "chat",
  "devin": "smart_toy",
  "devin-cli-agentic": "terminal",
  "devin-desktop": "desktop_windows",
  "digitalocean": "cloud",
  "docker-model-runner": "inventory_2",
  "doubao-web": "web",
  "duckduckgo-web": "search",
  "dxnt": "bolt",
  "electronhub": "bolt",
  "empower": "hub",
  "fastrouter": "rocket_launch",
  "felo-web": "search",
  "fenayai": "hub",
  "fish-audio": "record_voice_over",
  "fishaudio": "graphic_eq",
  "free-ai": "volunteer_activism",
  "freebuff": "bolt",
  "freeinference": "bolt",
  "friendliai": "group",
  "g4f-gemini": "bolt",
  "g4f-groq": "bolt",
  "g4f-nvidia": "bolt",
  "g4f-ollama": "bolt",
  "g4f-pollinations": "bolt",
  "galadriel": "auto_awesome",
  "gemini-business": "work",
  "gemini-web": "chat",
  "getgoapi": "rocket_launch",
  "ghe-copilot": "code",
  "gigachat": "bolt",
  "gitlab-duo": "code",
  "gitlawb-gmi": "gavel",
  "gladia": "record_voice_over",
  "glmt": "bolt",
  "hailuo-web": "video_library",
  "hcnsec": "security",
  "helixmind": "psychology",
  "helyxai": "auto_awesome",
  "heroku": "cloud",
  "huggingchat": "chat",
  "hyperagent": "flash_on",
  "imagen3": "image",
  "inner-ai": "psychology",
  "jules": "engineering",
  "kimi-coding-apikey": "code",
  "kimi-web": "chat",
  "laozhang": "hub",
  "lemonade": "bolt",
  "literouter": "router",
  "llama-cpp": "memory",
  "llamafile": "article",
  "llamagate": "gate",
  "llm-kiwi": "eco",
  "llmgateway": "gate",
  "lm-studio": "server",
  "lmarena": "emoji_events",
  "logfare": "receipt_long",
  "magnific": "image",
  "maritalk": "record_voice_over",
  "meganova-ai": "auto_awesome",
  "microsoft-designer-web": "image",
  "mixedbread": "hub",
  "mixlayer": "layers",
  "mlx-gemma": "memory",
  "mlx-qwen": "memory",
  "mnn-ai": "bolt",
  "moonshot": "bolt",
  "muse-code": "code",
  "muse-spark-web": "web",
  "naga-ac": "bolt",
  "naga-ai": "bolt",
  "nanogpt": "memory",
  "nara": "spa",
  "navy": "directions_boat",
  "ninerouter": "hub",
  "nomic": "hub",
  "notion-web": "web",
  "nscale": "scale",
  "oci": "cloud",
  "ofoxai": "bolt",
  "ollama-search": "search",
  "oobabooga": "dns",
  "opencode-zen": "code",
  "openference": "hub",
  "openference-api": "api",
  "openvecta": "hub",
  "opper": "bolt",
  "ovhcloud": "cloud",
  "piapi": "api",
  "poe-web": "chat",
  "poixe-ai": "auto_awesome",
  "pollinations": "flower",
  "predibase": "storage",
  "promptql": "query_stats",
  "publicai": "public",
  "qwen-web": "chat",
  "raycast": "bolt",
  "requesty": "swap_horiz",
  "rev-ai": "record_voice_over",
  "routeway": "signpost",
  "sap": "business",
  "sealion": "waves",
  "segmind": "image",
  "selfhosted-embedding": "cloud",
  "selfhosted-stt": "cloud",
  "selfhosted-tts": "cloud",
  "snowflake": "ac_unit",
  "soniox": "mic",
  "speechmatics": "record_voice_over",
  "speka": "record_voice_over",
  "suno": "music_note",
  "t3-web": "web",
  "tencent-aistudio-web": "web",
  "thebai": "hub",
  "theoldllm": "history",
  "tinycms-web": "web",
  "tinyfish": "language",
  "tokenreply": "reply",
  "triton": "developer_board",
  "uncloseai": "bolt",
  "unorouter": "router",
  "upstage": "theater_comedy",
  "v0-vercel-web": "code",
  "venice-web": "shield",
  "veoaifree-web": "video_library",
  "vllm": "memory",
  "void-ai": "circle",
  "volcengine": "cloud",
  "volcengine-agent-plan": "smart_toy",
  "volcengine-coding-plan": "code",
  "wafer": "layers",
  "wandb": "insights",
  "watsonx": "hub",
  "x-search": "tag",
  "xai-oauth": "bolt",
  "xinference": "hub",
  "yolo-auto": "directions_car",
  "yuanbao-web": "web",
  "zai": "bolt",
  "zai-web": "chat",
  "zcode": "code",
  "zed-hosted": "code",
  "zenmux-free": "hub",
  "zerolimitai": "all_inclusive",
  "zylo-api": "api",
};

// Two-letter monogram fallback by provider id (from registry display.textIcon).
const TEXT_ICON_BY_PROVIDER = {
  "agnes": "AG",
  "aimlapi": "AI",
  "alibaba": "QW",
  "ant-ling": "AN",
  "bai": "BA",
  "baichuan": "BA",
  "charm-hyper": "CH",
  "chenzk": "CH",
  "clova-studio": "CL",
  "coze": "CO",
  "crof": "CR",
  "dgrid": "DG",
  "dify": "DI",
  "dit": "DI",
  "doubao": "DO",
  "factory": "FA",
  "featherless-ai": "FE",
  "freeaiapikey": "FR",
  "freemodel-dev": "FR",
  "freetheai": "FR",
  "gitlawb": "GI",
  "haiper": "HA",
  "ideogram": "ID",
  "iflytek": "IF",
  "inception": "IN",
  "inference-net": "IN",
  "internlm": "IN",
  "kenari": "KE",
  "kie": "KI",
  "lambda-ai": "LA",
  "leonardo": "LE",
  "liquid": "LI",
  "meta-llama": "ME",
  "modal": "MO",
  "modelscope": "MO",
  "monsterapi": "MO",
  "nlpcloud": "NL",
  "nous-research": "NO",
  "nube": "NU",
  "ollama-cloud": "OL",
  "oneminai": "ON",
  "openadapter": "OP",
  "orcarouter": "OR",
  "pioneer": "PI",
  "plamo": "PL",
  "poe": "PO",
  "qianfan": "QI",
  "qiniu": "QI",
  "qwen-cloud": "QW",
  "qwen-cloud-token-plan": "QW",
  "regolo": "RE",
  "sarvam": "SA",
  "scaleway": "SC",
  "sensenova": "SE",
  "sparkdesk": "SP",
  "stepfun": "ST",
  "sumopod": "SU",
  "synthetic": "SY",
  "tabitoken": "TA",
  "token-kiosk": "TO",
  "typhoon": "TY",
  "udio": "UD",
  "v0-vercel": "V0",
  "writer": "WR",
  "x5lab": "X5",
  "xiaomi-mimo-token-plan": "XI",
  "yi": "YI",
  "zenmux": "ZE",
};


// Runtime cache — a 404 remembers the id so later mounts skip the request.
const failedIds = new Set();

function normalizeId(providerId) {
  if (!providerId || typeof providerId !== 'string') return '';
  return providerId.trim().toLowerCase();
}
function resolveId(providerId) {
  const id = normalizeId(providerId);
  return ICON_ALIASES[id] || id;
}

/** Type of icon to render for a provider id. */
export function getProviderIconKind(providerId) {
  const id = normalizeId(providerId);
  if (!id) return '';
  const aliased = resolveId(providerId);
  if (FILE_ICON_IDS.has(id) || FILE_ICON_IDS.has(aliased)) return FILE_ICON_EXT[id] || FILE_ICON_EXT[aliased] || 'png';
  if (SYMBOL_ICON_BY_PROVIDER[id] || SYMBOL_ICON_BY_PROVIDER[aliased]) return 'symbol';
  if (TEXT_ICON_BY_PROVIDER[id] || TEXT_ICON_BY_PROVIDER[aliased]) return 'text';
  return '';
}

/** File extension for the provider's real icon file (png/svg/webp), or "". */
export function getProviderIconExt(providerId) {
  const aliased = resolveId(providerId);
  return FILE_ICON_EXT[aliased] || '';
}

/** Icon file id (post-alias) for a provider with a real file, or "" if none/failed. */
export function resolveProviderIconId(providerId) {
  const id = normalizeId(providerId);
  if (!id) return '';
  const aliased = resolveId(providerId);
  if (failedIds.has(id) || failedIds.has(aliased)) return '';
  if (!(FILE_ICON_IDS.has(id) || FILE_ICON_IDS.has(aliased))) return '';
  return aliased;
}

/** Material Symbol for providers that use one. */
export function getProviderSymbolIcon(providerId) {
  const id = normalizeId(providerId);
  return SYMBOL_ICON_BY_PROVIDER[id] || SYMBOL_ICON_BY_PROVIDER[resolveId(providerId)] || '';
}

/** Text icon (display.textIcon) for a fallback. */
export function getProviderTextIcon(providerId) {
  const id = normalizeId(providerId);
  return TEXT_ICON_BY_PROVIDER[id] || TEXT_ICON_BY_PROVIDER[resolveId(providerId)] || '';
}

/** URL to the provider icon file, or null when there is none. */
export function getProviderIconSrc(providerId) {
  const id = resolveProviderIconId(providerId);
  if (!id) return null;
  const ext = FILE_ICON_EXT[id] || 'png';
  return `/providers/${id}.${ext}`;
}

/** Call from img onError so later mounts skip the request. */
export function markProviderIconMissing(providerId) {
  const id = normalizeId(providerId);
  if (id) failedIds.add(id);
  const aliased = ICON_ALIASES[id];
  if (aliased) failedIds.add(aliased);
}
